### ISSUE TITLE
Загрузка котировок акций.

### ISSUE THREAD

**Issue by fn-87** [ffeast/finam-export#11]
Привет. Мне понравилась ваша библиотека. Ваши примеры отлично работают, но вероятно в силу моего незнания получаю след. результат для получения котировок с рынка акций:
************
    exporter = Exporter()

    print('*** ALRS ***')
    rub = exporter.lookup(name='ALRS', market=Market.SHARES)
    assert len(rub) == 1
************
INFO:finam.export:Fetching https://www.finam.ru/profile/moex-akcii/gazprom/export/
INFO:finam.export:Fetching https://www.finam.ru/cache/N72Hgd54/icharts/icharts.js
DEBUG:finam.export:Parsing line starting with "var aEmitentIds = [1"
DEBUG:finam.export:Parsing line starting with "var aEmitentNames = "
DEBUG:finam.export:Parsing line starting with "var aEmitentCodes = "
DEBUG:finam.export:Parsing line starting with "var aEmitentMarkets "

Можете подсказать, как будет правильно написать чтобы получить нужную котировку акции?

**Comment by Ta-nu-ki** [comment]
from finam.export import Exporter, Market

exporter = Exporter()
print('*** ALRS ***')
rub = exporter.lookup(**code**='ALRS', market=Market.SHARES)
assert len(rub) == 1
**rub_id = rub.index[0]**
data = exporter.download(id_=**rub_id**, market=Market.SHARES)

**Comment by ffeast** [comment]
Seems to be solved, closing
