### ISSUE TITLE
Any wishes for the library?

### ISSUE THREAD

**Issue by ffeast** [ffeast/finam-export#2]
I see there're ~15 stargazers for this tool. 

Guys, is there anything missing in the library what's desperately needed so that it's worth spending spare time on it?
Feel free to comment in Russian if there are troubles writing in English

Thanks

**Comment by OlafGeorge** [comment]
Hey ffeast, my name is Olaf. I am very intermediate programmer, but I mainly study business.
I see that finam.ru has stock data to the minute. 
Unfortunately, I am not great at coding, can you help me access the "NASDAQ, Inc." that is found under US Stocks by writing a code for me that I can use in Python if that is okay with you?

**Comment by ffeast** [comment]
Hey @OlafGeorge 
Please create a separate issue if you still need it and I'll add an example to the source code
This issue is created for a different purpose

**Comment by netang** [comment]
Maybe it’s worth adding to the samples folder an example of receiving data with a timer? Finam API blocks connections if they are too frequent. I used `threading.Timer(3, ...)` to fix this problem.

**Comment by IS-live** [comment]
Finam changed its basic URL by adding a 'Token' argument - now it's 'http://export.finam.ru/export9.out?market={}&em={}&token={}...'
Automatic download is now also detected and banned
Could you please add Token retrieval fuctions to your code to deal with it?
Thanks!

**Comment by ffeast** [comment]
I haven't investigated deeply where this token is taken from and don't have much time to do that. From a brief analysis looks like it's picked up from re-captcha and it may complicate things. If anyone has looked into the mechanism in a greater detail it would be helpful

**Comment by ffeast** [comment]
Can't reproduce it anymore. Related ticket: https://github.com/ffeast/finam-export/issues/10
Closing this one
