### ISSUE TITLE
Финам включил токены

### ISSUE THREAD

**Issue by AndreyRzhaksinskiy** [ffeast/finam-export#20]
Ошибка аналогична
#https://github.com/ffeast/finam-export/issues/10
Преестали работать примеры по получению котировок.
На странице https://www.finam.ru/profile/mosbirzha-valyutnyj-rynok/eurrubtom-eur-rub/export/?market=41 при выгрузке появилось поле token.
В скрипте страницы:
```
		siteKey3: '6LcUHawUAAAAAKQF_5dMIorMoK57KgVQ444Q8IWN',
		getToken: function (callback, action) {
			grecaptcha.execute('6LcUHawUAAAAAKQF_5dMIorMoK444gVQQVBQ8IWN', { action: action || 'homepage' }).then(function (token) {
				callback(token);
			});
```

**Comment by AndreyRzhaksinskiy** [comment]
А в середине дня работоспособность восстановилась.

**Comment by ffeast** [comment]
Включали пару раз, в данный момент неактуально
Что делать, если включат опять - вопрос открытый
