### ISSUE TITLE
Can't add new cryptocurrencies market

### ISSUE THREAD

**Issue by vritme** [ffeast/finam-export#21]
I looked market number in html source - number 520 for crypto.
I added it in const.py file below other markets.
But always the same error - ivalid value for --market.  I even tried to delete or comment all other markets in const.py just to see what will happen - and program still has the same error.
Seems to be, that text of the error and array of markets doesn't go from const.py file, but somewhere from finam.ru.

What should i change in project files and what i should type in command prompt in order to add crypto quotes market and be able to download btc\eth ???

tried all queries in txt - nothing work.
[btc-quotes-query.txt](https://github.com/ffeast/finam-export/files/6042554/btc-quotes-query.txt)

Thank you.
![add market in const py](https://user-images.githubusercontent.com/42464402/109145862-e5386980-7784-11eb-86ff-88ca3e7cf3ca.jpg)
![can't download](https://user-images.githubusercontent.com/42464402/109145873-e8335a00-7784-11eb-91f5-553ceee07c9f.jpg)
![sber-market](https://user-images.githubusercontent.com/42464402/109145877-e9fd1d80-7784-11eb-94b9-1d840edaa45e.jpg)
![btc-market](https://user-images.githubusercontent.com/42464402/109145880-ebc6e100-7784-11eb-8227-00eac1cdcfd7.jpg)

**Comment by vritme** [comment]
Вроде бы подсказали - const берутся из установленного в систему pip пакета в директории с питон-клиентом, а не из const из папки с исходниками.

**Comment by InsonusK** [comment]
Crypto currency added in #27 . Everything works fine, waiting for merge.

**Comment by ffeast** [comment]
Merged, available in 5.1.1
