### ISSUE TITLE
1h forex data

### ISSUE THREAD

**Issue by mr6768** [ffeast/finam-export#23]
I Tried to fetch and download (csv) 1hour forex data, but it doesn't work.
can somebody help what I'm doing wrong?

python finam-download.py --market CURRENCIES_WORLD --timeframe HOURLY --destdir C:\Users

using the finam-download.py form scripts.

Thanks

**Comment by ffeast** [comment]
What's the error message?

**Comment by mr6768** [comment]
back then I couldn't fetch data for hourly but now it's working properly using the same script above.
thanks by the way
