### ISSUE TITLE
Getting error on export

### ISSUE THREAD

**Issue by brucelangford** [ffeast/finam-export#5]
```
from finam.export import Exporter, Market, LookupComparator, Timeframe
exporter = Exporter()
ref = exporter.lookup('AAPL', market=Market.USA) 
```

results in error: `FinamDownloadError: Unable to load https://www.finam.ru/profile/moex-akcii/gazprom/export/: <urlopen error [Errno -3] Temporary failure in name resolution>`

Could it be Finam recognizing that the request is not being made by a browser?

**Comment by ffeast** [comment]
From your error message It looks like a DNS problem, please try again. 
This code works fine for me (notice slight changes to lookup by code)

> from finam.export import Exporter, Market, LookupComparator, Timeframe
> 
> exporter = Exporter()
> ref = exporter.lookup(code='AAPL', market=Market.USA)
> print(ref)
> 
>

**Comment by brucelangford** [comment]
You are correct. The problem was on my end.
